GET http://localhost:8080/user-api/users

###

GET http://localhost:8080/user-api/users/vikas

###
POST http://localhost:8080/user-api/user
Content-Type: application/json

{
    
    "productname":"tv",
    "price":30000
}


### Update user by name
PUT http://localhost:8080/user-api/user/vikas
Content-Type: application/json

{
    "name":"vikas",
    "age":30,
    "salary":70000
}


### Delete user by id
DELETE http://localhost:8080/user-api/user/manasa


### PRODUCT Req
GET http://localhost:8080/product-api/products