GET http://localhost:8080/user-api/users

###

GET http://localhost:8080/user-api/users/100

###
POST http://localhost:8080/user-api/user
Content-Type: application/json

{
    "id":300,
    "name":"manasa",
    "age":25
}


### Update user by ID
PUT http://localhost:8080/user-api/user/100
Content-Type: application/json

{
    "id": 100,
    "name": "ravi kumar", 
    "age": 25 
}


### Delete user by id
DELETE http://localhost:8080/user-api/user/300


### PRODUCT Req
GET http://localhost:8080/product-api/products